# -*- coding: utf-8 -*-
"""pressure_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytYOlbr1yNQR_3oZvxqAQROK9zE3ersb
"""

import sys
import os
#sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'ITER_Equilibria'))
#sys.path.insert(0, os.path.dirname(__file__))

import numpy as np
from contourpy import contour_generator

from psi_anti_deriv_exact import G_total

from ExactSolutions import (
    psi1, psi2, psi3, psi4, psi5, psi6, psi7,
    psi8, psi9, psi10, psi11, psi12,
    psi1x, psi2x, psi3x, psi4x, psi5x, psi6x, psi7x,
    psi1y, psi2y, psi3y, psi4y, psi5y, psi6y, psi7y,
    psi1xx, psi2xx, psi3xx, psi4xx, psi5xx, psi6xx, psi7xx,
    psi1yy, psi2yy, psi3yy, psi4yy, psi5yy, psi6yy, psi7yy,
    psipart1, psipart2,
    psipart1x, psipart2x,
    psipart1y, psipart2y,
    psipart1xx, psipart2xx,
    psipart1yy, psipart2yy,
)


def make_psi(epsilon, kappa, delta, A=-0.05):
    """
    Solve the Solovev boundary-value problem for the given shape parameters
    and return a callable psi(x, y) that evaluates the poloidal flux function
    at arbitrary points.

    Parameters
    ----------
    epsilon : float  – inverse aspect ratio
    kappa   : float  – elongation
    delta   : float  – triangularity  (negative values are valid)
    A       : float  – pressure/current profile parameter (default -0.05)

    Returns
    -------
    psi : callable(x, y) -> float or ndarray
        Evaluates ψ at the point(s) (x, y).  x and y may be scalars or
        NumPy arrays of any shape.
    c : ndarray, shape (7,)
        Coefficients c[0]…c[6] for the homogeneous basis functions ψ₁…ψ₇.
    A : float
        The profile parameter (echoed back so callers need not track it).
    """
    alpha = np.arcsin(delta)
    curv1 = -(1 + alpha)**2 / (epsilon * kappa**2)
    curv2 = -kappa / (epsilon * np.cos(alpha)**2)
    curv3 = (1 - alpha)**2 / (epsilon * kappa**2)

    xhi = 1 - epsilon * delta
    yhi = kappa * epsilon

    M = np.array([
        [psi1(1+epsilon,0), psi2(1+epsilon,0), psi3(1+epsilon,0), psi4(1+epsilon,0), psi5(1+epsilon,0), psi6(1+epsilon,0), psi7(1+epsilon,0)],
        [psi1(1-epsilon,0), psi2(1-epsilon,0), psi3(1-epsilon,0), psi4(1-epsilon,0), psi5(1-epsilon,0), psi6(1-epsilon,0), psi7(1-epsilon,0)],
        [psi1(xhi,yhi),     psi2(xhi,yhi),     psi3(xhi,yhi),     psi4(xhi,yhi),     psi5(xhi,yhi),     psi6(xhi,yhi),     psi7(xhi,yhi)],
        [psi1x(xhi,yhi),    psi2x(xhi,yhi),    psi3x(xhi,yhi),    psi4x(xhi,yhi),    psi5x(xhi,yhi),    psi6x(xhi,yhi),    psi7x(xhi,yhi)],
        [curv1*psi1x(1+epsilon,0) + psi1yy(1+epsilon,0),
         curv1*psi2x(1+epsilon,0) + psi2yy(1+epsilon,0),
         curv1*psi3x(1+epsilon,0) + psi3yy(1+epsilon,0),
         curv1*psi4x(1+epsilon,0) + psi4yy(1+epsilon,0),
         curv1*psi5x(1+epsilon,0) + psi5yy(1+epsilon,0),
         curv1*psi6x(1+epsilon,0) + psi6yy(1+epsilon,0),
         curv1*psi7x(1+epsilon,0) + psi7yy(1+epsilon,0)],
        [curv3*psi1x(1-epsilon,0) + psi1yy(1-epsilon,0),
         curv3*psi2x(1-epsilon,0) + psi2yy(1-epsilon,0),
         curv3*psi3x(1-epsilon,0) + psi3yy(1-epsilon,0),
         curv3*psi4x(1-epsilon,0) + psi4yy(1-epsilon,0),
         curv3*psi5x(1-epsilon,0) + psi5yy(1-epsilon,0),
         curv3*psi6x(1-epsilon,0) + psi6yy(1-epsilon,0),
         curv3*psi7x(1-epsilon,0) + psi7yy(1-epsilon,0)],
        [curv2*psi1y(xhi,yhi) + psi1xx(xhi,yhi),
         curv2*psi2y(xhi,yhi) + psi2xx(xhi,yhi),
         curv2*psi3y(xhi,yhi) + psi3xx(xhi,yhi),
         curv2*psi4y(xhi,yhi) + psi4xx(xhi,yhi),
         curv2*psi5y(xhi,yhi) + psi5xx(xhi,yhi),
         curv2*psi6y(xhi,yhi) + psi6xx(xhi,yhi),
         curv2*psi7y(xhi,yhi) + psi7xx(xhi,yhi)],
    ])

    b = -np.array([
        A*psipart1(1+epsilon,0)  + (1-A)*psipart2(1+epsilon,0),
        A*psipart1(1-epsilon,0)  + (1-A)*psipart2(1-epsilon,0),
        A*psipart1(xhi,yhi)      + (1-A)*psipart2(xhi,yhi),
        A*psipart1x(xhi,yhi)     + (1-A)*psipart2x(xhi,yhi),
        A*(curv1*psipart1x(1+epsilon,0) + psipart1yy(1+epsilon,0))
            + (1-A)*(curv1*psipart2x(1+epsilon,0) + psipart2yy(1+epsilon,0)),
        A*(curv3*psipart1x(1-epsilon,0) + psipart1yy(1-epsilon,0))
            + (1-A)*(curv3*psipart2x(1-epsilon,0) + psipart2yy(1-epsilon,0)),
        A*(curv2*psipart1y(xhi,yhi) + psipart1xx(xhi,yhi))
            + (1-A)*(curv2*psipart2y(xhi,yhi) + psipart2xx(xhi,yhi)),
    ])

    C = np.linalg.solve(M, b)

    def psi(x, y):
        return (C[0]*psi1(x,y)  + C[1]*psi2(x,y)  + C[2]*psi3(x,y)  + C[3]*psi4(x,y)
              + C[4]*psi5(x,y)  + C[5]*psi6(x,y)  + C[6]*psi7(x,y)
              + A*psipart1(x,y) + (1-A)*psipart2(x,y))

    return psi, C, A



def extract_zero_contour(psi, x_lim, y_lim, n=500):
    """
    Extract the zero contour of psi(x, y) as a closed polygon.

    Evaluates psi on an n×n grid over [x_lim, y_lim], runs marching squares
    via contourpy, and returns the longest closed loop (the main plasma
    boundary, ignoring any spurious small loops near the grid edges).

    Parameters
    ----------
    psi   : callable(x, y) -> ndarray  – poloidal flux function
    x_lim : (float, float)             – (x_min, x_max) of the evaluation grid
    y_lim : (float, float)             – (y_min, y_max) of the evaluation grid
    n     : int                        – grid resolution per axis (default 500)

    Returns
    -------
    xs, ys : ndarray, shape (N+1,)
        Closed polygon vertices (first == last point).
    """
    x = np.linspace(x_lim[0], x_lim[1], n)
    y = np.linspace(y_lim[0], y_lim[1], n)
    X, Y = np.meshgrid(x, y)
    Z = psi(X, Y)

    gen = contour_generator(x=x, y=y, z=Z)
    lines = [l for l in gen.lines(0.0) if l is not None]

    if not lines:
        raise ValueError("No zero contour found within the specified domain.")

    # Keep the longest loop — that is the plasma boundary
    seg = np.asarray(max(lines, key=len))
    xs, ys = seg[:, 0].copy(), seg[:, 1].copy()

    # Ensure the polygon is explicitly closed
    if xs[0] != xs[-1] or ys[0] != ys[-1]:
        xs = np.append(xs, xs[0])
        ys = np.append(ys, ys[0])

    # Normalise to counterclockwise orientation (positive shoelace area)
    signed_area = 0.5 * np.sum(xs[:-1] * ys[1:] - xs[1:] * ys[:-1])
    if signed_area < 0:
        xs, ys = xs[::-1], ys[::-1]

    return xs, ys


def int_parametric_boundary(G, epsilon, kappa, delta, h):
    """
    Compute  ∬_Ω f(x,y) dxdy  via Green's theorem as a boundary line integral,
    where G is the y-antiderivative of f:  ∂G/∂y = f.

    By Green's theorem with a counterclockwise boundary (choosing P=-G, Q=0):

        ∬_Ω f dxdy  =  -∮_∂Ω G(x,y) dx
                     =  -∫_0^{2π} G(x(θ), y(θ)) · (dx/dθ) dθ

    The boundary ∂Ω is the Solovev parametric curve

        x(θ) = 1 + ε·cos(θ + arcsin(δ)·sin(θ))
        y(θ) = ε·κ·sin(θ),   θ ∈ [0, 2π]

    The integral over θ is approximated with the midpoint rule at step size h.

    Parameters
    ----------
    G       : callable(x, y) -> ndarray  – y-antiderivative of f, i.e. ∂G/∂y = f
    epsilon : float  – inverse aspect ratio
    kappa   : float  – elongation
    delta   : float  – triangularity
    h       : float  – step size in θ for the midpoint rule

    Returns
    -------
    integral : float

    Example
    -------
    from psi_anti_deriv_exact import G_total
    psi, c, A = make_psi(epsilon, kappa, delta)
    G = lambda x, y: G_total(x, y, A, c)
    result = int_parametric_boundary(G, epsilon, kappa, delta, h=0.01)
    """
    alpha = np.arcsin(delta)

    N = max(1, int(np.ceil(2.0 * np.pi / h)))
    dtheta = 2.0 * np.pi / N
    theta = (np.arange(N) + 0.5) * dtheta   # midpoints

    x = 1.0 + epsilon * np.cos(theta + alpha * np.sin(theta))
    y = epsilon * kappa * np.sin(theta)
    dxdtheta = -epsilon * np.sin(theta + alpha * np.sin(theta)) * (1.0 + alpha * np.cos(theta))

    return -float(np.sum(G(x, y) * dxdtheta) * dtheta)


def int_contour_boundary(G, xs, ys):
    """
    Compute  ∬_Ω f(x,y) dxdy  via Green's theorem using a piecewise-linear
    zero contour as the boundary, with the midpoint rule on each edge.

    Identical in principle to int_parametric_boundary but the boundary is
    supplied as a closed polygon (e.g. from extract_zero_contour) rather than
    the analytic parametric curve.

        ∬_Ω f dxdy  =  -∮_∂Ω G(x,y) dx
                     ≈  -∑_i  G(x_mid_i, y_mid_i) · Δx_i

    where the sum runs over all edges of the polygon, x_mid and y_mid are the
    edge midpoints, and Δx = x_{i+1} - x_i.

    Parameters
    ----------
    G    : callable(x, y) -> ndarray  – y-antiderivative of f, i.e. ∂G/∂y = f
    xs   : array-like, shape (N+1,)   – x-coordinates of closed polygon vertices
    ys   : array-like, shape (N+1,)   – y-coordinates of closed polygon vertices
                                        (first and last points must coincide)

    Returns
    -------
    integral : float
    """
    xs = np.asarray(xs, dtype=float)
    ys = np.asarray(ys, dtype=float)

    x0, x1 = xs[:-1], xs[1:]
    y0, y1 = ys[:-1], ys[1:]

    x_mid = 0.5 * (x0 + x1)
    y_mid = 0.5 * (y0 + y1)
    dx    = x1 - x0

    return -float(np.sum(G(x_mid, y_mid) * dx))


def get_vol_av_p_from_params(epsilon : float, kappa : float, delta : float, A : float = -0.5, method : str = 'contour', **kwargs):




    psi, c, _ = make_psi(epsilon, kappa, delta, A)

    G = lambda x, y: G_total(x, y, A, c)

    func_for_vol = lambda x,y: x*y
    if method == 'parametric':
        h = kwargs.get('h',0.1)
        if h <= 0:
            raise ValueError("Step size h must be non zero and positive for parametric method.")
        num = int_parametric_boundary(G,epsilon,kappa,delta,h=h)
        denom = int_parametric_boundary(func_for_vol,epsilon,kappa,delta,h=h)

        return -(1-A)*num/denom
    elif method == 'contour':
        N = kwargs.get('N',500)
        if N <=0 or not isinstance(N, int):
            raise ValueError("Grid resolution N must be a positive integer for contour method.")
        xs, ys = extract_zero_contour(psi, x_lim=(0, 2), y_lim=(-1,1), n=N)                                    #x and y lims are hard coded... should be figures out programatically by finding limits of parametric curve.
        num = int_contour_boundary(G, xs, ys)
        denom = int_contour_boundary(func_for_vol, xs, ys)
        return -(1-A)*num/denom
    elif method == 'masking':
        N = kwargs.get('N',500)
        if N <= 0 or not isinstance(N, int):
            raise ValueError("Grid resolution N must be a positive integer for masking method.")
        return int_masking(epsilon,kappa,delta,A, N)  # TODO: implement masking method
    else:
        raise ValueError(f"Unknown method: {method}")


def int_masking(epsilon,kappa,delta,A, N):
  mu0 = 4 * np.pi * 1e-7
  R0 = 1.0
  psi0 = 1.0

  psi, _, _ = make_psi(epsilon, kappa, delta, A)



  x = np.linspace(1 - epsilon, 1 + epsilon, N)
  y = np.linspace(-kappa * epsilon, kappa * epsilon, N)

  dx = x[1] - x[0]
  dy = y[1] - y[0]
  dA = dx * dy

  X, Y = np.meshgrid(x, y)

  PSI = psi(X, Y)

# 1 inside plasma, 0 outside
  indicator = (PSI <= 0).astype(float)

# physical pressure
#P = -(psi0**2 / (mu0 * R0**4)) * (1 - A) * PSI
  P = -(1 - A) * PSI

# numerator: ∬_Ω x p dA
  numerator = dA * np.sum(X * P * indicator)

# denominator: ∬_Ω x dA
  denominator = dA * np.sum(X * indicator)

  p_avg = numerator / denominator

  return p_avg