# -*- coding: utf-8 -*-
"""pressure_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytYOlbr1yNQR_3oZvxqAQROK9zE3ersb
"""

import sys
import os
#sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'ITER_Equilibria'))
#sys.path.insert(0, os.path.dirname(__file__))

import numpy as np
from contourpy import contour_generator

from psi_anti_deriv_exact import G_total

from ExactSolutions import (
    psi1, psi2, psi3, psi4, psi5, psi6, psi7,
    psi8, psi9, psi10, psi11, psi12,
    psi1x, psi2x, psi3x, psi4x, psi5x, psi6x, psi7x,
    psi1y, psi2y, psi3y, psi4y, psi5y, psi6y, psi7y,
    psi1xx, psi2xx, psi3xx, psi4xx, psi5xx, psi6xx, psi7xx,
    psi1yy, psi2yy, psi3yy, psi4yy, psi5yy, psi6yy, psi7yy,
    psipart1, psipart2,
    psipart1x, psipart2x,
    psipart1y, psipart2y,
    psipart1xx, psipart2xx,
    psipart1yy, psipart2yy,
)


def make_psi(epsilon, kappa, delta, A=-0.05):
    """
    Solve the Solovev boundary-value problem for the given shape parameters
    and return a callable psi(x, y) that evaluates the poloidal flux function
    at arbitrary points.

    Parameters
    ----------
    epsilon : float  – inverse aspect ratio
    kappa   : float  – elongation
    delta   : float  – triangularity  (negative values are valid)
    A       : float  – pressure/current profile parameter (default -0.05)

    Returns
    -------
    psi : callable(x, y) -> float or ndarray
        Evaluates ψ at the point(s) (x, y).  x and y may be scalars or
        NumPy arrays of any shape.
    c : ndarray, shape (7,)
        Coefficients c[0]…c[6] for the homogeneous basis functions ψ₁…ψ₇.
    A : float
        The profile parameter (echoed back so callers need not track it).
    """
    alpha = np.arcsin(delta)
    curv1 = -(1 + alpha)**2 / (epsilon * kappa**2)
    curv2 = -kappa / (epsilon * np.cos(alpha)**2)
    curv3 = (1 - alpha)**2 / (epsilon * kappa**2)

    xhi = 1 - epsilon * delta
    yhi = kappa * epsilon

    M = np.array([
        [psi1(1+epsilon,0), psi2(1+epsilon,0), psi3(1+epsilon,0), psi4(1+epsilon,0), psi5(1+epsilon,0), psi6(1+epsilon,0), psi7(1+epsilon,0)],
        [psi1(1-epsilon,0), psi2(1-epsilon,0), psi3(1-epsilon,0), psi4(1-epsilon,0), psi5(1-epsilon,0), psi6(1-epsilon,0), psi7(1-epsilon,0)],
        [psi1(xhi,yhi),     psi2(xhi,yhi),     psi3(xhi,yhi),     psi4(xhi,yhi),     psi5(xhi,yhi),     psi6(xhi,yhi),     psi7(xhi,yhi)],
        [psi1x(xhi,yhi),    psi2x(xhi,yhi),    psi3x(xhi,yhi),    psi4x(xhi,yhi),    psi5x(xhi,yhi),    psi6x(xhi,yhi),    psi7x(xhi,yhi)],
        [curv1*psi1x(1+epsilon,0) + psi1yy(1+epsilon,0),
         curv1*psi2x(1+epsilon,0) + psi2yy(1+epsilon,0),
         curv1*psi3x(1+epsilon,0) + psi3yy(1+epsilon,0),
         curv1*psi4x(1+epsilon,0) + psi4yy(1+epsilon,0),
         curv1*psi5x(1+epsilon,0) + psi5yy(1+epsilon,0),
         curv1*psi6x(1+epsilon,0) + psi6yy(1+epsilon,0),
         curv1*psi7x(1+epsilon,0) + psi7yy(1+epsilon,0)],
        [curv3*psi1x(1-epsilon,0) + psi1yy(1-epsilon,0),
         curv3*psi2x(1-epsilon,0) + psi2yy(1-epsilon,0),
         curv3*psi3x(1-epsilon,0) + psi3yy(1-epsilon,0),
         curv3*psi4x(1-epsilon,0) + psi4yy(1-epsilon,0),
         curv3*psi5x(1-epsilon,0) + psi5yy(1-epsilon,0),
         curv3*psi6x(1-epsilon,0) + psi6yy(1-epsilon,0),
         curv3*psi7x(1-epsilon,0) + psi7yy(1-epsilon,0)],
        [curv2*psi1y(xhi,yhi) + psi1xx(xhi,yhi),
         curv2*psi2y(xhi,yhi) + psi2xx(xhi,yhi),
         curv2*psi3y(xhi,yhi) + psi3xx(xhi,yhi),
         curv2*psi4y(xhi,yhi) + psi4xx(xhi,yhi),
         curv2*psi5y(xhi,yhi) + psi5xx(xhi,yhi),
         curv2*psi6y(xhi,yhi) + psi6xx(xhi,yhi),
         curv2*psi7y(xhi,yhi) + psi7xx(xhi,yhi)],
    ])

    b = -np.array([
        A*psipart1(1+epsilon,0)  + (1-A)*psipart2(1+epsilon,0),
        A*psipart1(1-epsilon,0)  + (1-A)*psipart2(1-epsilon,0),
        A*psipart1(xhi,yhi)      + (1-A)*psipart2(xhi,yhi),
        A*psipart1x(xhi,yhi)     + (1-A)*psipart2x(xhi,yhi),
        A*(curv1*psipart1x(1+epsilon,0) + psipart1yy(1+epsilon,0))
            + (1-A)*(curv1*psipart2x(1+epsilon,0) + psipart2yy(1+epsilon,0)),
        A*(curv3*psipart1x(1-epsilon,0) + psipart1yy(1-epsilon,0))
            + (1-A)*(curv3*psipart2x(1-epsilon,0) + psipart2yy(1-epsilon,0)),
        A*(curv2*psipart1y(xhi,yhi) + psipart1xx(xhi,yhi))
            + (1-A)*(curv2*psipart2y(xhi,yhi) + psipart2xx(xhi,yhi)),
    ])

    C = np.linalg.solve(M, b)

    def psi(x, y):
        return (C[0]*psi1(x,y)  + C[1]*psi2(x,y)  + C[2]*psi3(x,y)  + C[3]*psi4(x,y)
              + C[4]*psi5(x,y)  + C[5]*psi6(x,y)  + C[6]*psi7(x,y)
              + A*psipart1(x,y) + (1-A)*psipart2(x,y))

    return psi, C, A



def extract_zero_contour(psi, x_lim, y_lim, n=500):
    """
    Extract the zero contour of psi(x, y) as a closed polygon.

    Evaluates psi on an n×n grid over [x_lim, y_lim], runs marching squares
    via contourpy, and returns the longest closed loop (the main plasma
    boundary, ignoring any spurious small loops near the grid edges).

    Parameters
    ----------
    psi   : callable(x, y) -> ndarray  – poloidal flux function
    x_lim : (float, float)             – (x_min, x_max) of the evaluation grid
    y_lim : (float, float)             – (y_min, y_max) of the evaluation grid
    n     : int                        – grid resolution per axis (default 500)

    Returns
    -------
    xs, ys : ndarray, shape (N+1,)
        Closed polygon vertices (first == last point).
    """
    x = np.linspace(x_lim[0], x_lim[1], n)
    y = np.linspace(y_lim[0], y_lim[1], n)
    X, Y = np.meshgrid(x, y)
    Z = psi(X, Y)

    gen = contour_generator(x=x, y=y, z=Z)
    lines = [l for l in gen.lines(0.0) if l is not None]

    if not lines:
        raise ValueError("No zero contour found within the specified domain.")

    # Keep the longest loop — that is the plasma boundary
    seg = np.asarray(max(lines, key=len))
    xs, ys = seg[:, 0].copy(), seg[:, 1].copy()

    # Ensure the polygon is explicitly closed
    if xs[0] != xs[-1] or ys[0] != ys[-1]:
        xs = np.append(xs, xs[0])
        ys = np.append(ys, ys[0])

    # Normalise to counterclockwise orientation (positive shoelace area)
    signed_area = 0.5 * np.sum(xs[:-1] * ys[1:] - xs[1:] * ys[:-1])
    if signed_area < 0:
        xs, ys = xs[::-1], ys[::-1]

    return xs, ys


def int_contour_boundary(G, xs, ys):
    """
    Compute  ∬_Ω f(x,y) dxdy  via Green's theorem using a piecewise-linear
    zero contour as the boundary, with the midpoint rule on each edge.

        ∬_Ω f dxdy  =  -∮_∂Ω G(x,y) dx
                     ≈  -∑_i  G(x_mid_i, y_mid_i) · Δx_i

    where the sum runs over all edges of the polygon, x_mid and y_mid are the
    edge midpoints, and Δx = x_{i+1} - x_i.

    Parameters
    ----------
    G    : callable(x, y) -> ndarray  – y-antiderivative of f, i.e. ∂G/∂y = f
    xs   : array-like, shape (N+1,)   – x-coordinates of closed polygon vertices
    ys   : array-like, shape (N+1,)   – y-coordinates of closed polygon vertices
                                        (first and last points must coincide)

    Returns
    -------
    integral : float
    """
    xs = np.asarray(xs, dtype=float)
    ys = np.asarray(ys, dtype=float)

    x0, x1 = xs[:-1], xs[1:]
    y0, y1 = ys[:-1], ys[1:]

    x_mid = 0.5 * (x0 + x1)
    y_mid = 0.5 * (y0 + y1)
    dx    = x1 - x0

    return -float(np.sum(G(x_mid, y_mid) * dx))


def get_vol_av_p_from_params(epsilon, kappa, delta, A: float = -0.5, method: str = 'contour', **kwargs):




    if np.ndim(epsilon) > 0 or np.ndim(kappa) > 0 or np.ndim(delta) > 0:
        _scalar = lambda e, k, d: get_vol_av_p_from_params(e, k, d, A, method, **kwargs)
        return np.vectorize(_scalar)(epsilon, kappa, delta)

    psi, c, _ = make_psi(epsilon, kappa, delta, A)

    G = lambda x, y: G_total(x, y, A, c)

    func_for_vol = lambda x,y: x*y
    if method == 'contour':
        N = kwargs.get('N',500)
        if N <=0 or not isinstance(N, int):
            raise ValueError("Grid resolution N must be a positive integer for contour method.")
        xs, ys = extract_zero_contour(psi, x_lim=(0, 2), y_lim=(-1,1), n=N)                                    #x and y lims are hard coded... should be figures out programatically by finding limits of parametric curve.
        num = int_contour_boundary(G, xs, ys)
        denom = int_contour_boundary(func_for_vol, xs, ys)
        return -(1-A)*num/denom
    elif method == 'masking':
        N = kwargs.get('N',500)
        if N <= 0 or not isinstance(N, int):
            raise ValueError("Grid resolution N must be a positive integer for masking method.")
        return int_masking(psi, epsilon, kappa, A, N)
    else:
        raise ValueError(f"Unknown method: {method}")


def _compute_psi_min(psi, epsilon, kappa, N=500):
    """
    Return the minimum (most negative) value of psi inside the zero contour.

    Evaluates psi on an NxN grid over the plasma extent with 0.1 padding and
    returns the minimum of all grid points where psi <= 0.
    """
    x_lim = (1 - epsilon - 0.1, 1 + epsilon + 0.1)
    y_lim = (-kappa * epsilon - 0.1, kappa * epsilon + 0.1)
    x_g = np.linspace(x_lim[0], x_lim[1], N)
    y_g = np.linspace(y_lim[0], y_lim[1], N)
    PSI_g = psi(*np.meshgrid(x_g, y_g))
    interior = PSI_g[PSI_g <= 0]
    if interior.size == 0:
        raise ValueError("No interior points found; check domain bounds.")
    return float(np.min(interior))


def normalized_psi_pressure(epsilon, kappa, delta, A: float = -0.5,
                              method: str = 'contour', **kwargs):
    """
    Volume-averaged normalised pressure: same as get_vol_av_p_from_params but
    integrates  psi / psi_min  instead of  psi, where psi_min is the minimum
    (most negative) value of psi inside the zero contour.

    Parameters
    ----------
    epsilon : float  – inverse aspect ratio
    kappa   : float  – elongation
    delta   : float  – triangularity
    A       : float  – Solov'ev profile parameter (default -0.5)
    method  : str    – 'contour' or 'masking'
    **kwargs         – N (int, grid resolution, default 500)

    Returns
    -------
    p_norm : float
    """
    if np.ndim(epsilon) > 0 or np.ndim(kappa) > 0 or np.ndim(delta) > 0:
        _scalar = lambda e, k, d: normalized_psi_pressure(e, k, d, A, method, **kwargs)
        return np.vectorize(_scalar)(epsilon, kappa, delta)

    psi, c, _ = make_psi(epsilon, kappa, delta, A)

    N = kwargs.get('N', 500)
    if not isinstance(N, int) or N <= 0:
        raise ValueError("Grid resolution N must be a positive integer.")

    x_lim = (1 - epsilon - 0.1, 1 + epsilon + 0.1)
    y_lim = (-kappa * epsilon - 0.1, kappa * epsilon + 0.1)

    func_for_vol = lambda x, y: x * y

    psi_min = _compute_psi_min(psi, epsilon, kappa, N=N)

    if method == 'contour':
        xs, ys = extract_zero_contour(psi, x_lim, y_lim, n=N)
        G_norm = lambda x, y: G_total(x, y, A, c) / psi_min
        num   = int_contour_boundary(G_norm, xs, ys)
        denom = int_contour_boundary(func_for_vol, xs, ys)
        return num / denom

    elif method == 'masking':
        x = np.linspace(1 - epsilon, 1 + epsilon, N)
        y = np.linspace(-kappa * epsilon, kappa * epsilon, N)
        X, Y = np.meshgrid(x, y)
        PSI = psi(X, Y)
        indicator = (PSI <= 0).astype(float)
        dA = (x[1] - x[0]) * (y[1] - y[0])
        P_norm = PSI / psi_min
        return float(dA * np.sum(X * P_norm * indicator) /
                     (dA * np.sum(X * indicator)))

    else:
        raise ValueError(f"Unknown method: '{method}'. Choose 'contour' or 'masking'.")



def beta_t_alternative(epsilon, kappa, delta, A=-0.5, N=500):
    """
    Compute an alternative beta_toroidal:

        beta_t = B_0 * epsilon^2 * beta_poloidal(epsilon, kappa, delta, A) * inv_q_star^2

    where B_0 = 1/2 is chosen so that beta_t_alternative == normalized_psi_pressure.

    Parameters
    ----------
    epsilon : float  – inverse aspect ratio
    kappa   : float  – elongation
    delta   : float  – triangularity
    A       : float  – Solov'ev profile parameter (default -0.5)
    N       : int    – grid resolution (default 500)

    Returns
    -------
    beta_t : float
    """

    if np.ndim(epsilon) > 0 or np.ndim(kappa) > 0 or np.ndim(delta) > 0:
        _scalar = lambda e, k, d: beta_t_alternative(e, k, d, A, N)
        return np.vectorize(_scalar)(epsilon, kappa, delta)

    bp = beta_poloidal(epsilon, kappa, delta, A, N)
    iq = inv_q_star(epsilon, kappa, delta, A, N=N)

    return epsilon**2 * bp * iq**2


def inv_q_star(epsilon, kappa, delta, A=-0.5, R_0=1.0, N=500):
    """
    Compute the inverse cylindrical safety factor 1/q*.

        psi_0_squared = -R_0^4 / ((1-A) * psi_min)
        1/q*          = -(sqrt(psi_0_squared) / (epsilon * R_0^2 * B_0)) * (1/C_p) * integral_factor

    where:
      psi_min         = minimum (magnetic-axis) value of psi inside the zero contour
      C_p             = poloidal circumference of the plasma boundary
      integral_factor = ∬_Ω [A + (1-A)x²]/x dxdy

    Parameters
    ----------
    epsilon : float  – inverse aspect ratio
    kappa   : float  – elongation
    delta   : float  – triangularity
    A       : float  – Solov'ev profile parameter (default -0.5)
    R_0     : float  – major radius normalization (default 1.0, cancels in the formula)
    N       : int    – grid resolution (default 500)

    Returns
    -------
    inv_q : float
    """
    if np.ndim(epsilon) > 0 or np.ndim(kappa) > 0 or np.ndim(delta) > 0:
        _scalar = lambda e, k, d: inv_q_star(e, k, d, A, R_0, N)
        return np.vectorize(_scalar)(epsilon, kappa, delta)

    psi, _, _ = make_psi(epsilon, kappa, delta, A)

    psi_min       = _compute_psi_min(psi, epsilon, kappa, N=N)
    psi_0_squared = -R_0**4 / ((1 - A) * psi_min)

    x_lim = (1 - epsilon - 0.1, 1 + epsilon + 0.1)
    y_lim = (-kappa * epsilon - 0.1, kappa * epsilon + 0.1)

    xs, ys = extract_zero_contour(psi, x_lim, y_lim, n=N)

    C_p             = poloidal_circum(xs, ys)
    integral_factor = integral_multiplier(epsilon, kappa, delta, A, N=N)

    B_0 = 2
    return -(np.sqrt(psi_0_squared) / (epsilon * R_0**2*B_0)) * (1 / C_p) * integral_factor


def int_masking(psi, epsilon, kappa, A, N):
  x = np.linspace(1 - epsilon, 1 + epsilon, N)
  y = np.linspace(-kappa * epsilon, kappa * epsilon, N)

  dx = x[1] - x[0]
  dy = y[1] - y[0]
  dA = dx * dy

  X, Y = np.meshgrid(x, y)

  PSI = psi(X, Y)

# 1 inside plasma, 0 outside
  indicator = (PSI <= 0).astype(float)

# physical pressure
#P = -(psi0**2 / (mu0 * R0**4)) * (1 - A) * PSI
  P = -(1 - A) * PSI

# numerator: ∬_Ω x p dA
  numerator = dA * np.sum(X * P * indicator)

# denominator: ∬_Ω x dA
  denominator = dA * np.sum(X * indicator)

  p_avg = numerator / denominator

  return p_avg


def poloidal_circum(xs, ys) -> float:
    """
    Approximate the poloidal circumference of a closed polygon.

    Sums the Euclidean lengths of all edges of the polygon, which should be
    the zero contour of psi obtained from extract_zero_contour.

    Parameters
    ----------
    xs : array-like, shape (N+1,)  – x-coordinates of closed polygon vertices
    ys : array-like, shape (N+1,)  – y-coordinates of closed polygon vertices

    Returns
    -------
    circumference : float
    """
    xs = np.asarray(xs, dtype=float)
    ys = np.asarray(ys, dtype=float)

    dx = xs[1:] - xs[:-1]
    dy = ys[1:] - ys[:-1]

    return float(np.sum(np.sqrt(dx**2 + dy**2)))


def integral_multiplier(epsilon: float, kappa: float, delta: float,
                        A: float, N: int = 500) -> float:
    """
    Compute  iint_Omega  [A + (1-A)*x^2] / x  dx dy

    using the Green's theorem contour method.  The y-antiderivative of the
    integrand f(x,y) = A/x + (1-A)*x  is  G(x,y) = y*[A/x + (1-A)*x].

    Parameters
    ----------
    epsilon : float  – inverse aspect ratio
    kappa   : float  – elongation
    delta   : float  – triangularity
    A       : float  – Solov'ev profile parameter
    N       : int    – marching-squares grid resolution for the zero contour

    Returns
    -------
    value : float
    """
    psi, _, _ = make_psi(epsilon, kappa, delta, A)

    x_lim = (1 - epsilon - 0.1, 1 + epsilon + 0.1)
    y_lim = (-kappa * epsilon - 0.1, kappa * epsilon + 0.1)

    xs, ys = extract_zero_contour(psi, x_lim, y_lim, n=N)

    G = lambda x, y: y * (A / x + (1 - A) * x)

    return int_contour_boundary(G, xs, ys)


def beta_poloidal(epsilon, kappa=None, delta=None, A=-0.5, N=500):
    arr = np.asarray(epsilon, dtype=float)
    if arr.ndim == 2 and arr.shape[1] == 3:
        epsilon, kappa, delta = arr[:, 0], arr[:, 1], arr[:, 2]
    elif kappa is None or delta is None:
        raise ValueError("kappa and delta are required when epsilon is not an Nx3 array")

    if np.ndim(epsilon) > 0 or np.ndim(kappa) > 0 or np.ndim(delta) > 0:
        _scalar = lambda e, k, d: beta_poloidal(e, k, d, A, N)
        return np.vectorize(_scalar)(epsilon, kappa, delta)

    psi, c, _ = make_psi(epsilon, kappa, delta, A)

    x_lim = (1 - epsilon - 0.1, 1 + epsilon + 0.1)
    y_lim = (-kappa * epsilon - 0.1, kappa * epsilon + 0.1)

    xs, ys = extract_zero_contour(psi, x_lim, y_lim, n=N)

    circum       = poloidal_circum(xs, ys)
    volume       = int_contour_boundary(lambda x, y: x * y, xs, ys)
    psi_integral = int_contour_boundary(lambda x, y: G_total(x, y, A, c), xs, ys)
    factor       = int_contour_boundary(lambda x, y: y * (A / x + (1 - A) * x), xs, ys)

    beta_p = -2 * (1 - A) * (circum**2 / volume) * psi_integral * factor**(-2)

    return beta_p



def beta_toroidal(epsilon, kappa=None, delta=None, A=-0.5, q=2, N=500):
    arr = np.asarray(epsilon, dtype=float)
    if arr.ndim == 2 and arr.shape[1] == 3:
        epsilon, kappa, delta = arr[:, 0], arr[:, 1], arr[:, 2]
    elif kappa is None or delta is None:
        raise ValueError("kappa and delta are required when epsilon is not an Nx3 array")

    if np.ndim(epsilon) > 0 or np.ndim(kappa) > 0 or np.ndim(delta) > 0:
        _scalar = lambda e, k, d: beta_toroidal(e, k, d, A, q, N)
        return np.vectorize(_scalar)(epsilon, kappa, delta)

    beta_p = beta_poloidal(epsilon, kappa, delta, A, N)
    return epsilon**2 * beta_p / q**2


MU_0 = 4 * np.pi * 1e-7  # magnetic permeability of free space [T·m/A]


def beta_poloidal_updated(shape_params: tuple, R_0: float, I: float,
                          A: float = -0.5, N: int = 500) -> float:
    """
    Compute the poloidal beta from physical parameters:

        beta_p = (4π² ε² R_0² (1 + κ²) / (μ_0 I²)) * <p>

    where <p> = normalized_psi_pressure(ε, κ, δ, A) is the volume-averaged
    pressure normalised by psi_min.

    Parameters
    ----------
    shape_params : tuple (epsilon, kappa, delta)
        epsilon – inverse aspect ratio
        kappa   – elongation
        delta   – triangularity
    R_0          : float – major radius [m]
    I            : float – plasma current [A]
    A            : float – Solov'ev profile parameter (default -0.5)
    N            : int   – grid resolution (default 500)

    Returns
    -------
    beta_p : float
    """
    epsilon, kappa, delta = shape_params

    p_avg  = normalized_psi_pressure(epsilon, kappa, delta, A=A, N=N)
    prefactor = (4 * np.pi**2 * epsilon**2 * R_0**2 * (1 + kappa**2)) / (MU_0 * I**2)

    return prefactor * p_avg


def q_star_updated(shape_params: tuple, R_0: float, I: float, B_0: float) -> float:
    """
    Compute the cylindrical safety factor q* from physical parameters:

        q* = 2π ε² R_0² B_0 (1 + κ²) / (2 μ_0 R_0 I)

    Parameters
    ----------
    shape_params : tuple (epsilon, kappa, delta)
        epsilon – inverse aspect ratio
        kappa   – elongation
        delta   – triangularity  (unused in this formula, included for consistency)
    R_0  : float – major radius [m]
    I    : float – plasma current [A]
    B_0  : float – toroidal magnetic field at the magnetic axis [T]

    Returns
    -------
    q_star : float
    """
    epsilon, kappa, _ = shape_params

    return (2 * np.pi * epsilon**2 * R_0**2 * B_0 * (1 + kappa**2)) / (2 * MU_0 * R_0 * I)


def beta_toroidal_updated(shape_params: tuple, R_0: float, I: float, B_0: float,
                          A: float = -0.5, N: int = 500) -> float:
    """
    Compute the toroidal beta from physical parameters:

        beta_t = (ε² * beta_p_updated / q*_updated²) * (1 + κ²) / 2

    Parameters
    ----------
    shape_params : tuple (epsilon, kappa, delta)
        epsilon – inverse aspect ratio
        kappa   – elongation
        delta   – triangularity
    R_0  : float – major radius [m]
    I    : float – plasma current [A]
    B_0  : float – toroidal magnetic field at the magnetic axis [T]
    A    : float – Solov'ev profile parameter (default -0.5)
    N    : int   – grid resolution for pressure integral (default 500)

    Returns
    -------
    beta_t : float
    """
    epsilon, kappa, _ = shape_params

    beta_p = beta_poloidal_updated(shape_params, R_0, I, A=A, N=N)
    q_star = q_star_updated(shape_params, R_0, I, B_0)

    return (epsilon**2 * beta_p / q_star**2) * (1 + kappa**2) / 2
