# -*- coding: utf-8 -*-
"""genetic_testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aW2UsMispMZ3UTN33VAsCbVOfioPlSe9
"""

import genetic_algorithms as ga
import numpy as np

num_generations  = 10                 ###number of generations
population_size  = 40                 ###number of individuals per generation

epsilon_range = (0.1,  0.45)
kappa_range   = (1.0,  1.7)
delta_range   = (-0.3, 0.3)

population = ga.initialize_population(population_size,
                                      epsilon_range, kappa_range, delta_range)        ###initializing population. creates that N x 3 array.

best_params  = np.zeros(3)                                                            ### array of 0's [0,0,0].]
best_fitness = -np.inf

for gen in range(num_generations):                                                   ###go through all teh generations.
    fitness = ga.evaluate_population(population, A=-0.5, method='contour', N=200)    ###evaluate fitness (for every individual, calculate average pressure).

    # track global best
    gen_best_idx = np.argmax(fitness)                              ###FINDS the winner of this generation.
    if fitness[gen_best_idx] > best_fitness:                       ###if the winner is greater than the best fitness value, then add that in.
        best_fitness = fitness[gen_best_idx]                       ###update the best fitness value.
        best_params  = population[gen_best_idx].copy()             #stores actual parameter values.

    print(f"gen {gen+1:3d}/{num_generations}  "
          f"best={best_fitness:.6f}  "
          f"mean={fitness.mean():.6f}  "
          f"(eps={best_params[0]:.3f}, kap={best_params[1]:.3f}, dlt={best_params[2]:.3f})")

    parents_a, parents_b = ga.select_parents(population, fitness, k=10)       ###choose stronger individuals to become parents with high fitness values.

    offspring = ga.crossover(parents_a, parents_b, method='blx_alpha', alpha=0.05) ###crossing over parent a and parent b and producing the offspring. Mixes parent genes.

    mutated_offspring = ga.mutate(offspring, 0.05,
                                  epsilon_range, kappa_range, delta_range)         ###mutations in the offspring computed here.

    # elitism: carry the top 1% of the current population into the next generation
    n_elite = max(1, int(0.01 * population_size))                                  ###keep the best individual alive.
    elite_idx = np.argsort(fitness)[-n_elite:]                                     ###find the strongest individual.
    mutated_offspring[:n_elite] = population[elite_idx]                            ###copy directly into next generation.
    population = mutated_offspring                                                 ###new generation.

print()
print("═" * 55)
print("Best individual found:")
print(f"  epsilon : {best_params[0]:.6f}")
print(f"  kappa   : {best_params[1]:.6f}")
print(f"  delta   : {best_params[2]:.6f}")
print(f"  fitness : {best_fitness:.6f}")
print("═" * 55)

import genetic_algorithms as ga
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings("ignore", category=RuntimeWarning)

# -----------------------------
# Parameter ranges
# -----------------------------
epsilon_range = (0.1,  0.45)
kappa_range   = (1.0,  1.7)
delta_range   = (-0.3, 0.3)

A = -0.5
method = "contour"
N_grid = 200

# -----------------------------
# GA settings to test
# -----------------------------
experiments = [
    {"population_size": 20, "num_generations": 10},    ###runs 20 individuals across 10 generations.
    {"population_size": 40, "num_generations": 10},    ###runs 40 individuals across 10 generattions...
    {"population_size": 60, "num_generations": 10},
    {"population_size": 40, "num_generations": 20},
]

results = []

# -----------------------------
# Run experiments
# -----------------------------
for exp_id, exp in enumerate(experiments, start=1):     ###looping through experiments (exp_id: experiment number, exp: actual dictionary - popsize: _, numgenerations: _)

    population_size = exp["population_size"]
    num_generations = exp["num_generations"]

    population = ga.initialize_population(              ###creating starting population.
        population_size,
        epsilon_range,
        kappa_range,
        delta_range
    )

    best_params = np.zeros(3)
    best_fitness = -np.inf

    for gen in range(num_generations):             ###evolution loop.

        fitness = ga.evaluate_population(         ###calculates fitness in each generation.
            population,
            A=A,
            method=method,
            N=N_grid
        )

        gen_best_idx = np.argmax(fitness)                 ###finds best individuals.

        if fitness[gen_best_idx] > best_fitness:         ###updates best ever.
            best_fitness = fitness[gen_best_idx]
            best_params = population[gen_best_idx].copy()

        parents_a, parents_b = ga.select_parents(population, fitness, k=10)

        offspring = ga.crossover(
            parents_a,
            parents_b,
            method="blx_alpha",
            alpha=0.05
        )

        mutated_offspring = ga.mutate(
            offspring,
            0.05,
            epsilon_range,
            kappa_range,
            delta_range
        )

        n_elite = max(1, int(0.01 * population_size))
        elite_idx = np.argsort(fitness)[-n_elite:]
        mutated_offspring[:n_elite] = population[elite_idx]

        population = mutated_offspring

    results.append({
        "experiment": exp_id,
        "population_size": population_size,
        "num_generations": num_generations,
        "best_epsilon": best_params[0],
        "best_kappa": best_params[1],
        "best_delta": best_params[2],
        "best_fitness": best_fitness
    })

# -----------------------------
###Results
# -----------------------------
results_df = pd.DataFrame(results)

print("\nGA Experiment Results")
print("=" * 80)
print(results_df.to_string(index=False))
print("=" * 80)

import matplotlib.pyplot as plt

# nicer printed table
display(results_df.round(4))

# -----------------------------
# Plot 1: Best fitness by experiment
# -----------------------------
plt.figure(figsize=(7, 4))
plt.plot(results_df["experiment"], results_df["best_fitness"], marker="o")
plt.xlabel("Experiment")
plt.ylabel("Best fitness")
plt.title("Best Fitness Across GA Experiments")
plt.grid(True, alpha=0.3)
plt.show()

# -----------------------------
# Plot 2: Best parameters by experiment
# -----------------------------
plt.figure(figsize=(7, 4))
plt.plot(results_df["experiment"], results_df["best_epsilon"], marker="o", label="epsilon")
plt.plot(results_df["experiment"], results_df["best_kappa"], marker="o", label="kappa")
plt.plot(results_df["experiment"], results_df["best_delta"], marker="o", label="delta")
plt.xlabel("Experiment")
plt.ylabel("Best parameter value")
plt.title("Best Parameters Found Across Experiments")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# -----------------------------
# Plot 3: Best fitness vs population size
# -----------------------------
plt.figure(figsize=(7, 4))
plt.scatter(results_df["population_size"], results_df["best_fitness"], s=80)
plt.xlabel("Population size")
plt.ylabel("Best fitness")
plt.title("Effect of Population Size on Best Fitness")
plt.grid(True, alpha=0.3)

import genetic_algorithms as ga
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings("ignore", category=RuntimeWarning)

# -----------------------------
# Parameter ranges
# -----------------------------
epsilon_range = (0.05,  0.5)
kappa_range   = (0.5,  2.0)
delta_range   = (-0.5, 0.5)

A = -0.5
method = "contour"
N_grid = 200

# -----------------------------
# GA settings to test
# -----------------------------
experiments = [
    {"population_size": 20, "num_generations": 10},    ###runs 20 individuals across 10 generations.
    {"population_size": 40, "num_generations": 10},    ###runs 40 individuals across 10 generattions...
    {"population_size": 60, "num_generations": 10},
    {"population_size": 40, "num_generations": 20},
]

results = []

# -----------------------------
# Run experiments
# -----------------------------
for exp_id, exp in enumerate(experiments, start=1):     ###looping through experiments (exp_id: experiment number, exp: actual dictionary - popsize: _, numgenerations: _)

    population_size = exp["population_size"]
    num_generations = exp["num_generations"]

    population = ga.initialize_population(              ###creating starting population.
        population_size,
        epsilon_range,
        kappa_range,
        delta_range
    )

    best_params = np.zeros(3)
    best_fitness = -np.inf

    for gen in range(num_generations):             ###evolution loop.

        fitness = ga.evaluate_population(         ###calculates fitness in each generation.
            population,
            A=A,
            method=method,
            N=N_grid
        )

        gen_best_idx = np.argmax(fitness)                 ###finds best individuals.

        if fitness[gen_best_idx] > best_fitness:         ###updates best ever.
            best_fitness = fitness[gen_best_idx]
            best_params = population[gen_best_idx].copy()

        parents_a, parents_b = ga.select_parents(population, fitness, k=10)

        offspring = ga.crossover(
            parents_a,
            parents_b,
            method="blx_alpha",
            alpha=0.05
        )

        mutated_offspring = ga.mutate(
            offspring,
            0.05,
            epsilon_range,
            kappa_range,
            delta_range
        )

        n_elite = max(1, int(0.01 * population_size))
        elite_idx = np.argsort(fitness)[-n_elite:]
        mutated_offspring[:n_elite] = population[elite_idx]

        population = mutated_offspring

    results.append({
        "experiment": exp_id,
        "population_size": population_size,
        "num_generations": num_generations,
        "best_epsilon": best_params[0],
        "best_kappa": best_params[1],
        "best_delta": best_params[2],
        "best_fitness": best_fitness
    })

###Results
# -----------------------------
results_df = pd.DataFrame(results)

print("\nGA Experiment Results")
print("=" * 80)
print(results_df.to_string(index=False))
print("=" * 80)

import matplotlib.pyplot as plt

# nicer printed table
display(results_df.round(4))

# -----------------------------
# Plot 1: Best fitness by experiment
# -----------------------------
plt.figure(figsize=(7, 4))
plt.plot(results_df["experiment"], results_df["best_fitness"], marker="o")
plt.xlabel("Experiment")
plt.ylabel("Best fitness")
plt.title("Best Fitness Across GA Experiments")
plt.grid(True, alpha=0.3)
plt.show()

# -----------------------------
# Plot 2: Best parameters by experiment
# -----------------------------
plt.figure(figsize=(7, 4))
plt.plot(results_df["experiment"], results_df["best_epsilon"], marker="o", label="epsilon")
plt.plot(results_df["experiment"], results_df["best_kappa"], marker="o", label="kappa")
plt.plot(results_df["experiment"], results_df["best_delta"], marker="o", label="delta")
plt.xlabel("Experiment")
plt.ylabel("Best parameter value")
plt.title("Best Parameters Found Across Experiments")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# -----------------------------
# Plot 3: Best fitness vs population size
# -----------------------------
plt.figure(figsize=(7, 4))
plt.scatter(results_df["population_size"], results_df["best_fitness"], s=80)
plt.xlabel("Population size")
plt.ylabel("Best fitness")
plt.title("Effect of Population Size on Best Fitness")
plt.grid(True, alpha=0.3)

import matplotlib.pyplot as plt
import pressure_utils as pu

# Convert results to DataFrame if you haven't already
results_df = pd.DataFrame(results)

# Pick the overall best row
best_row = results_df.loc[results_df["best_fitness"].idxmax()]

epsilon = best_row["best_epsilon"]
kappa   = best_row["best_kappa"]
delta   = best_row["best_delta"]

print("Best sanity-check parameters:")
print("epsilon =", epsilon)
print("kappa   =", kappa)
print("delta   =", delta)
print("fitness =", best_row["best_fitness"])

# Build plasma function psi(x,y)
psi, c, _ = pu.make_psi(epsilon, kappa, delta, A=A)

# Grid for plotting
x = np.linspace(0, 2, 400)
y = np.linspace(-1.5, 1.5, 400)
X, Y = np.meshgrid(x, y)
Z = psi(X, Y)

plt.figure(figsize=(6, 6))

# Shade the inside of the plasma: psi <= 0
plt.contourf(X, Y, Z <= 0, levels=[0.5, 1], alpha=0.4)

# Draw the plasma boundary: psi = 0
plt.contour(X, Y, Z, levels=[0], colors="black", linewidths=2)

plt.xlabel("x")
plt.ylabel("y")
plt.title(
    f"Best plasma shape sanity check\n"
    f"ε={epsilon:.3f}, κ={kappa:.3f}, δ={delta:.3f}, fitness={best_row['best_fitness']:.3f}"
)
plt.axis("equal")
plt.grid(True, alpha=0.3)
plt.show()



###The resulting shape appears highly irregular, consisting of multiple disconnected contour regions rather than a single closed plasma boundary.
###Optimal parameters (ϵ,κ,δ)=(0.05,0.5,−0.5) lie exactly on the limits of the allowed parameter ranges.
###Suggests that the large fitness value (≈313) may be associated with a numerical artifact or a degenerate configuration rather than a physically
###realistic plasma shape.